### ISSUE TITLE
TypeError: laravel is not a function after fresh install

### ISSUE THREAD

**Issue by chrisvasey** [ozziexsh/laravel-jetstream-react#37]
Hello!

I had this issue today when trying to run `npm run build` or `npm run dev` after a fresh install:
```
failed to load config from /project/path/vite.config.ts
error when starting dev server:
TypeError: laravel is not a function
    at file:///project/path/vite.config.ts.timestamp-1684530596781.mjs:7:5
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadConfigFromBundledFile (file:///project/path/node_modules/vite/dist/node/chunks/dep-1889fec9.js:63135:21)
    at async loadConfigFromFile (file:///project/path/node_modules/vite/dist/node/chunks/dep-1889fec9.js:63020:28)
    at async resolveConfig (file:///project/path/node_modules/vite/dist/node/chunks/dep-1889fec9.js:62643:28)
    at async createServer (file:///project/path/node_modules/vite/dist/node/chunks/dep-1889fec9.js:61943:20)
    at async CAC.<anonymous> (file:///project/path/node_modules/vite/dist/node/cli.js:707:24)
```

Laravel Version:  10.10
Jetstream Version: 3.2

I suspect the new version of Jetstream.
I have found that bumping my `laravel-vite-plugin` in my package.json from `^0.5.4` to `^0.7.7` resolves the issue.
~When I get a second, I can try to write a pull request for this.~

I love this package. It has become how I start every project!

**Comment by ozziexsh** [comment]
glad to hear you find it useful :) and thanks for the fix

released as v0.5.1 in [ce222b7](https://github.com/ozziexsh/laravel-jetstream-react/commit/ce222b7ff648147f0d52b12673adf414700d2e3a)
